#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = yii\helpers\ArrayHelper::merge(
    [
        'id' => 'console',
        'basePath' => __DIR__,
    ],
    require __DIR__ . '/config/main-local.php',
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
